ci: disable frontend-code-quality job

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -353,53 +353,53 @@ frontend-lint:
   tags:
     - no-cache
 
-frontend-code-quality:
-  stage: test
-  image: docker:latest
-  allow_failure: true
-  services:
-    - docker:dind
-  variables:
-    DOCKER_DRIVER: overlay2
-    DOCKER_TLS_CERTDIR: ""
-    CODE_QUALITY_IMAGE: "registry.gitlab.com/gitlab-org/ci-cd/codequality:0.85.10-gitlab.1"
-  needs: []
-  before_script:
-    - source ./Frontend/code-quality-env.sh
-    - export SOURCE_CODE=$PWD/Frontend/gis
-  script:
-#    - |
-#      if ! docker info &>/dev/null; then
-#        if [ -z "$DOCKER_HOST" -a "$KUBERNETES_PORT" ]; then
-#          export DOCKER_HOST='tcp://localhost:2375'
-#        fi
-#      fi
-    - docker pull --quiet "$CODE_QUALITY_IMAGE"
-    - |
-      docker run \
-        $(propagate_env_vars \
-          SOURCE_CODE \
-          TIMEOUT_SECONDS \
-          CODECLIMATE_DEBUG \
-          CODECLIMATE_DEV \
-          REPORT_STDOUT \
-          ENGINE_MEMORY_LIMIT_BYTES \
-        ) \
-        --volume "$PWD":/code \
-        --volume /var/run/docker.sock:/var/run/docker.sock \
-        "$CODE_QUALITY_IMAGE" /code
-  artifacts:
-    reports:
-      codequality: gl-code-quality-report.json
-    expire_in: 4 weeks
-  dependencies: []
-  rules:
-    - if: '$CODE_QUALITY_DISABLED'
-      when: never
-    - if: '$CI_COMMIT_TAG || $CI_COMMIT_BRANCH'
-  retry: 2
-  tags:
-    - docker-build
+# frontend-code-quality:
+#   stage: test
+#   image: docker:latest
+#   allow_failure: true
+#   services:
+#     - docker:dind
+#   variables:
+#     DOCKER_DRIVER: overlay2
+#     DOCKER_TLS_CERTDIR: ""
+#     CODE_QUALITY_IMAGE: "registry.gitlab.com/gitlab-org/ci-cd/codequality:0.85.10-gitlab.1"
+#   needs: []
+#   before_script:
+#     - source ./Frontend/code-quality-env.sh
+#     - export SOURCE_CODE=$PWD/Frontend/gis
+#   script:
+# #    - |
+# #      if ! docker info &>/dev/null; then
+# #        if [ -z "$DOCKER_HOST" -a "$KUBERNETES_PORT" ]; then
+# #          export DOCKER_HOST='tcp://localhost:2375'
+# #        fi
+# #      fi
+#     - docker pull --quiet "$CODE_QUALITY_IMAGE"
+#     - |
+#       docker run \
+#         $(propagate_env_vars \
+#           SOURCE_CODE \
+#           TIMEOUT_SECONDS \
+#           CODECLIMATE_DEBUG \
+#           CODECLIMATE_DEV \
+#           REPORT_STDOUT \
+#           ENGINE_MEMORY_LIMIT_BYTES \
+#         ) \
+#         --volume "$PWD":/code \
+#         --volume /var/run/docker.sock:/var/run/docker.sock \
+#         "$CODE_QUALITY_IMAGE" /code
+#   artifacts:
+#     reports:
+#       codequality: gl-code-quality-report.json
+#     expire_in: 4 weeks
+#   dependencies: []
+#   rules:
+#     - if: '$CODE_QUALITY_DISABLED'
+#       when: never
+#     - if: '$CI_COMMIT_TAG || $CI_COMMIT_BRANCH'
+#   retry: 2
+#   tags:
+#     - docker-build
 
 check-missing-translations:
   stage: test
